questions =  [
    {"id": 0, "question": "There should be bold or thick borders between countries.", "effects": {"prog": 1}},
    {"id": 1, "question": "Borders should be solid lines instead of dashes and dots.", "effects": {"prog": 1}},
    {"id": 2, "question": "There should be an outline for coasts.", "effects": {"prog": 1}},
    {"id": 3, "question": "If the terrain is highlighted, it should be through shades, than through full textures.", "effects": {"right": 1}},
    {"id": 4, "question": "Indicating ocean depths is pointless.", "effects": {"right": 1}},
    {"id": 5, "question": "Colors should focus more upon polities, than on terrain.", "effects": {"right": 1}},
    {"id": 6, "question": "Color palettes should be more distinct than two or three colors.", "effects": {"prog": 1}},
    {"id": 7, "question": "A texture to indicate water is a must.", "effects": {"prog": 1}},
    {"id": 8, "question": "It is better that color palettes for counteies be consistent across videos.", "effects": {"prog": 1}},
    {"id": 9, "question": "When mapping a war, color palettes should be for factions rather than every distinct country when possible.", "effects": {"right": 1}},
    {"id": 10, "question": "Vassals and puppet states should be shown distinctly in some form.", "effects": {"auth": 1}},
    {"id": 11, "question": "Autonomous areas should be shown distinctly in some form.", "effects": {"auth": 1}},
    {"id": 12, "question": "Nomadic tribes should be shown with boundaries of some kind.", "effects": {"auth": -1}},
    {"id": 13, "question": "Disputed borders or territories should be indicated whenever possible.", "effects": {"auth": -1}},
    {"id": 14, "question": "As a general rule, de facto over de jure..", "effects": {"right": 1}},
    {"id": 15, "question": "Insurgencies and guerillas should be shown whenever they control any territory.", "effects": {"auth": 1}},
    {"id": 16, "question": "Areas with guerilla activity should be shown even when they don't control any territory.", "effects": {"auth":-1}},
    {"id": 17, "question": "Frontlines should be based on active control rather than broad control.", "effects": {"auth": 1}},
    {"id": 18, "question": "It is better to show different shades of control rather than a decisive front whenever possible.", "effects": {"auth":-1}},
    {"id": 19, "question": "During raids or incursions, they should be a moving blob separate from the front lines rather than extending from them.", "effects": {"auth":-1}},
    {"id": 20, "question": "Countries should be labelled whenever possible.", "effects": {"right": 1}},
    {"id": 21, "question": "Capitals and major cities should be labelled whenever possible.", "effects": {"right": 1}},
    {"id": 22, "question": "Mountain ranges should be labelled whenever possible.", "effects": {"prog": 1}},
    {"id": 23, "question": "Oceans and seas should be labelled whenever possible.", "effects": {"prog": 1}},
    {"id": 24, "question": "Major rivers should be labelled whenever possible.", "effects": {"auth": -1}},
    {"id": 25, "question": "There should be different fonts on the map compared to the key.", "effects": {"auth": -1}},
    {"id": 26, "question": "The legend should have a textured background instead of a solid color.", "effects": {"prog": 1}},
    {"id": 27, "question": "There should be some frames that go around the map or the map legend.", "effects": {"right": 1}},
    {"id": 28, "question": "One should use color, tilting, and transparency with labels whenever possible.", "effects": {"auth": -1}},
    {"id": 29, "question": "Jake Mapping did nothing wrong - It is preferrable to release frequently within areas you possess little knowledge of.", "effects": {"auth": -1}},
    {"id": 30, "question": "If you have nothing to map, you have nothing to fear ; there must not even be a pixel of inaccuracy within a video.", "effects": {"auth": 1}},
    {"id": 31, "question": "It is only right to criticize a mapper in order to promote growth within them.", "effects": {"auth": 1}},
    {"id": 32, "question": "Vector mapping is a social construct, and not a natural state of affairs.", "effects": {"prog": 1}},
    {"id": 33, "question": "Shapefiles deserve further recognition and Orion did nothing wrong.", "effects": {"auth": 1}},
    {"id": 34, "question": "Mapping is a hobby first, and academic second.", "effects": {"prog": 1}},
];